#!/usr/bin/env bash
# ==============================================================================
# NoteMark - Comprehensive Build & Automation Script
# ==============================================================================
# This script provides a unified, robust interface for building, testing,
# linting, analyzing, and packaging the NoteMark Android application.
# ==============================================================================

set -euo pipefail

# ------------------------------------------------------------------------------
# Script & Project Constants
# ------------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${SCRIPT_DIR}"
GRADLEW="${PROJECT_ROOT}/gradlew"
LOCAL_PROPERTIES="${PROJECT_ROOT}/local.properties"
START_TIME=$(date +%s)

# ------------------------------------------------------------------------------
# Color / Text Formatting Support
# ------------------------------------------------------------------------------
if [[ -t 1 ]] && [[ "${NO_COLOR:-}" != "1" ]] && [[ "${TERM:-}" != "dumb" ]]; then
    BOLD="\033[1m"
    DIM="\033[2m"
    RED="\033[0;31m"
    GREEN="\033[0;32m"
    YELLOW="\033[0;33m"
    BLUE="\033[0;34m"
    MAGENTA="\033[0;35m"
    CYAN="\033[0;36m"
    WHITE="\033[1;37m"
    RESET="\033[0m"
else
    BOLD=""
    DIM=""
    RED=""
    GREEN=""
    YELLOW=""
    BLUE=""
    MAGENTA=""
    CYAN=""
    WHITE=""
    RESET=""
fi

# ------------------------------------------------------------------------------
# Logging & Helper Functions
# ------------------------------------------------------------------------------
log_info() {
    echo -e "${CYAN}[INFO]${RESET} $*"
}

log_step() {
    echo -e "\n${BOLD}${BLUE}==>${RESET} ${BOLD}${WHITE}$*${RESET}"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${RESET} $*"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${RESET} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${RESET} $*" >&2
}

format_time() {
    local seconds=$1
    local min=$((seconds / 60))
    local sec=$((seconds % 60))
    if ((min > 0)); then
        printf "%dm %ds" "$min" "$sec"
    else
        printf "%ds" "$sec"
    fi
}

human_readable_size() {
    local file="$1"
    if [[ -f "$file" ]]; then
        if [[ "$OSTYPE" == "darwin"* ]]; then
            stat -f%z "$file" | awk '{ split("B KB MB GB", v); s=1; while($1>1024 && s<4){$1/=1024; s++} printf "%.2f %s", $1, v[s] }'
        else
            stat -c%s "$file" | awk '{ split("B KB MB GB", v); s=1; while($1>1024 && s<4){$1/=1024; s++} printf "%.2f %s", $1, v[s] }'
        fi
    else
        echo "0 B"
    fi
}

print_banner() {
    echo -e "${BOLD}${CYAN}"
    echo "================================================================================"
    echo "                      NoteMark Project Build System                             "
    echo "================================================================================"
    echo -e "${RESET}"
}

# ------------------------------------------------------------------------------
# Pre-flight Checks
# ------------------------------------------------------------------------------
check_prerequisites() {
    log_info "Checking build environment and prerequisites..."

    # Ensure gradlew exists and is executable
    if [[ ! -f "$GRADLEW" ]]; then
        log_error "Gradle wrapper (gradlew) not found at: $GRADLEW"
        exit 1
    fi

    if [[ ! -x "$GRADLEW" ]]; then
        log_warn "Setting executable permissions on gradlew..."
        chmod +x "$GRADLEW"
    fi

    # Check Java
    if command -v java >/dev/null 2>&1; then
        local java_ver
        java_ver=$(java -version 2>&1 | head -n 1)
        log_info "Java runtime: ${DIM}${java_ver}${RESET}"
    else
        log_error "Java is not installed or not available in PATH."
        exit 1
    fi

    # Check local.properties and required configuration
    if [[ ! -f "$LOCAL_PROPERTIES" ]]; then
        log_warn "local.properties not found! Creating default template..."
        cat << 'EOF' > "$LOCAL_PROPERTIES"
## Autogenerated local.properties template
# Location of the SDK. This is only used by Gradle.
# sdk.dir=/path/to/android/sdk
HEADER_VALUE_FOR_NOTE_MARK_API=local_dev_key
EOF
        log_warn "Created local.properties with placeholder HEADER_VALUE_FOR_NOTE_MARK_API."
    else
        if ! grep -q "^HEADER_VALUE_FOR_NOTE_MARK_API" "$LOCAL_PROPERTIES"; then
            log_warn "HEADER_VALUE_FOR_NOTE_MARK_API missing in local.properties. Appending placeholder..."
            echo "HEADER_VALUE_FOR_NOTE_MARK_API=local_dev_key" >> "$LOCAL_PROPERTIES"
        fi
    fi

    # Git details if available
    if command -v git >/dev/null 2>&1 && git -C "$PROJECT_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        local branch commit_sha
        branch=$(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
        commit_sha=$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
        log_info "Git: ${DIM}branch=${branch}, commit=${commit_sha}${RESET}"
    fi
}

# ------------------------------------------------------------------------------
# Usage & Help
# ------------------------------------------------------------------------------
show_help() {
    print_banner
    cat << EOF
Usage: ./build.sh [COMMAND] [OPTIONS]

COMMANDS:
  all | full            Run complete pipeline: clean, stability, lint, test, assemble (default)
  build | assemble      Assemble application packages (APKs/AABs based on options)
  debug                 Shortcut to assemble Debug APK
  release               Shortcut to assemble Release APK & App Bundle
  bundle                Assemble Android App Bundle (.aab)
  test | unit-test      Run unit tests
  lint                  Run Android Lint static analysis
  lint-fix              Run Android Lint and apply safe automatic fixes
  stability             Run Compose stability checks (stabilityCheck)
  stability-dump        Generate / update Compose stability reference dump
  check | verify        Run all quality checks: stabilityCheck, lint, and unit tests
  clean                 Clean build directories and caches
  install-debug         Build and install Debug APK on connected Android device/emulator
  connected-test        Run instrumented tests on connected Android device/emulator
  diagnostics | info    Print environment, Android SDK, Java, and project diagnostics
  help | -h | --help    Show this help message

OPTIONS:
  -v, --variant <type>  Target specific variant: 'debug', 'release', or 'all' (default: all)
  -c, --clean           Perform clean before running target command
  -t, --test            Include unit test execution during build/assemble
  -l, --lint            Include lint analysis during build/assemble
  -s, --stability       Include Compose stability verification during build/assemble
  --apk                 Build APK output only (default for build/assemble)
  --aab                 Build Android App Bundle (.aab) output only
  --all-artifacts       Build both APK (.apk) and App Bundle (.aab)
  --skip-tests          Skip running unit tests in compound targets
  --skip-lint           Skip running lint checks in compound targets
  --skip-stability      Skip Compose stability checks in compound targets
  --dry-run             Print the Gradle command that would run without executing it
  --stop-daemon         Stop running Gradle daemons
  --offline             Run Gradle in offline mode
  --no-daemon           Do not use Gradle daemon (recommended for CI environments)
  --parallel            Enable Gradle parallel execution (default: enabled)
  --refresh-deps        Refresh Gradle dependencies
  --stacktrace          Print full stacktrace on Gradle error
  --info                Run Gradle with informational logging
  --scan                Publish a Gradle build scan
  -q, --quiet           Quiet mode (reduce output)

EXAMPLES:
  ./build.sh full                       # Run full validation and build all variants
  ./build.sh debug                      # Build debug APK quickly
  ./build.sh release                    # Build optimized release APK and Bundle
  ./build.sh test                       # Run all unit tests
  ./build.sh test -v debug              # Run debug unit tests only
  ./build.sh check                      # Run lint, tests, and stability checks
  ./build.sh assemble -v release --aab  # Build release App Bundle
  ./build.sh clean build -t -l          # Clean, test, lint, and assemble

EOF
}

# ------------------------------------------------------------------------------
# Command & Flag Parsing
# ------------------------------------------------------------------------------
COMMAND="all"
VARIANT="all"
FLAG_CLEAN=0
FLAG_TEST=0
FLAG_LINT=0
FLAG_STABILITY=0
FLAG_BUILD_APK=0
FLAG_BUILD_AAB=0
SKIP_TESTS=0
SKIP_LINT=0
SKIP_STABILITY=0
DRY_RUN=0
GRADLE_ARGS=()

parse_arguments() {
    local positional_args=()

    while [[ $# -gt 0 ]]; do
        case "$1" in
            help|-h|--help)
                show_help
                exit 0
                ;;
            all|full)
                COMMAND="all"
                shift
                ;;
            build|assemble)
                COMMAND="assemble"
                shift
                ;;
            debug)
                COMMAND="debug"
                VARIANT="debug"
                shift
                ;;
            release)
                COMMAND="release"
                VARIANT="release"
                shift
                ;;
            bundle)
                COMMAND="bundle"
                shift
                ;;
            test|unit-test)
                COMMAND="test"
                shift
                ;;
            lint)
                COMMAND="lint"
                shift
                ;;
            lint-fix)
                COMMAND="lint-fix"
                shift
                ;;
            stability|stability-check)
                COMMAND="stability"
                shift
                ;;
            stability-dump)
                COMMAND="stability-dump"
                shift
                ;;
            check|verify)
                COMMAND="check"
                shift
                ;;
            clean)
                COMMAND="clean"
                shift
                ;;
            install-debug)
                COMMAND="install-debug"
                VARIANT="debug"
                shift
                ;;
            connected-test)
                COMMAND="connected-test"
                shift
                ;;
            diagnostics|info)
                COMMAND="diagnostics"
                shift
                ;;
            -v|--variant)
                if [[ -n "${2:-}" && "$2" != -* ]]; then
                    VARIANT="$2"
                    shift 2
                else
                    log_error "Option --variant requires an argument (debug, release, or all)."
                    exit 1
                fi
                ;;
            -c|--clean)
                FLAG_CLEAN=1
                shift
                ;;
            -t|--test)
                FLAG_TEST=1
                shift
                ;;
            -l|--lint)
                FLAG_LINT=1
                shift
                ;;
            -s|--stability)
                FLAG_STABILITY=1
                shift
                ;;
            --apk)
                FLAG_BUILD_APK=1
                shift
                ;;
            --aab|--bundle)
                FLAG_BUILD_AAB=1
                shift
                ;;
            --all-artifacts)
                FLAG_BUILD_APK=1
                FLAG_BUILD_AAB=1
                shift
                ;;
            --skip-tests)
                SKIP_TESTS=1
                shift
                ;;
            --skip-lint)
                SKIP_LINT=1
                shift
                ;;
            --skip-stability)
                SKIP_STABILITY=1
                shift
                ;;
            --dry-run)
                DRY_RUN=1
                shift
                ;;
            --stop-daemon)
                COMMAND="stop-daemon"
                shift
                ;;
            --offline)
                GRADLE_ARGS+=("--offline")
                shift
                ;;
            --no-daemon)
                GRADLE_ARGS+=("--no-daemon")
                shift
                ;;
            --parallel)
                GRADLE_ARGS+=("--parallel")
                shift
                ;;
            --refresh-deps)
                GRADLE_ARGS+=("--refresh-dependencies")
                shift
                ;;
            --stacktrace)
                GRADLE_ARGS+=("--stacktrace")
                shift
                ;;
            --info)
                GRADLE_ARGS+=("--info")
                shift
                ;;
            --scan)
                GRADLE_ARGS+=("--scan")
                shift
                ;;
            -q|--quiet)
                GRADLE_ARGS+=("-q")
                shift
                ;;
            *)
                log_error "Unknown argument or command: $1"
                echo "Run './build.sh --help' for usage instructions."
                exit 1
                ;;
        esac
    done

    # Default build artifact type if not specified
    if [[ $FLAG_BUILD_APK -eq 0 && $FLAG_BUILD_AAB -eq 0 ]]; then
        FLAG_BUILD_APK=1
    fi
}

# ------------------------------------------------------------------------------
# Gradle Execution Wrapper
# ------------------------------------------------------------------------------
run_gradle() {
    local task_desc="$1"
    shift
    local tasks=("$@")

    if [[ ${#tasks[@]} -eq 0 ]]; then
        return 0
    fi

    log_step "$task_desc"
    log_info "Executing Gradle tasks: ${BOLD}${tasks[*]}${RESET}"
    if [[ ${#GRADLE_ARGS[@]} -gt 0 ]]; then
        log_info "Extra Gradle flags: ${DIM}${GRADLE_ARGS[*]}${RESET}"
    fi

    if [[ $DRY_RUN -eq 1 ]]; then
        if [[ ${#GRADLE_ARGS[@]} -gt 0 ]]; then
            echo -e "${YELLOW}[DRY-RUN]${RESET} Would run: $GRADLEW ${tasks[*]} ${GRADLE_ARGS[*]}"
        else
            echo -e "${YELLOW}[DRY-RUN]${RESET} Would run: $GRADLEW ${tasks[*]}"
        fi
        return 0
    fi

    local task_start
    task_start=$(date +%s)

    # Run the gradle wrapper
    if [[ ${#GRADLE_ARGS[@]} -gt 0 ]]; then
        "$GRADLEW" "${tasks[@]}" "${GRADLE_ARGS[@]}"
    else
        "$GRADLEW" "${tasks[@]}"
    fi

    local task_end
    task_end=$(date +%s)
    local task_duration=$((task_end - task_start))
    log_success "$task_desc completed in $(format_time $task_duration)"
}

# ------------------------------------------------------------------------------
# Diagnostics Command
# ------------------------------------------------------------------------------
run_diagnostics() {
    print_banner
    log_step "Project & Environment Diagnostics"
    echo -e "${BOLD}Project Directory:${RESET}  $PROJECT_ROOT"
    echo -e "${BOLD}Operating System:${RESET}   $(uname -srm)"
    echo -e "${BOLD}Shell:${RESET}              $SHELL ($BASH_VERSION)"
    
    echo -e "\n${BOLD}Java Environment:${RESET}"
    if command -v java >/dev/null 2>&1; then
        java -version 2>&1 | sed 's/^/  /'
        echo "  JAVA_HOME: ${JAVA_HOME:-<not set>}"
    else
        echo "  Java not found!"
    fi

    echo -e "\n${BOLD}Android SDK Environment:${RESET}"
    echo "  ANDROID_HOME:     ${ANDROID_HOME:-<not set>}"
    echo "  ANDROID_SDK_ROOT: ${ANDROID_SDK_ROOT:-<not set>}"
    if [[ -f "$LOCAL_PROPERTIES" ]]; then
        echo "  local.properties sdk.dir: $(grep '^sdk\.dir' "$LOCAL_PROPERTIES" 2>/dev/null || echo '<not set>')"
    fi

    echo -e "\n${BOLD}Gradle Wrapper:${RESET}"
    "$GRADLEW" --version | sed 's/^/  /'
}

# ------------------------------------------------------------------------------
# Artifact Collection and Summary
# ------------------------------------------------------------------------------
print_summary() {
    local end_time
    end_time=$(date +%s)
    local total_duration=$((end_time - START_TIME))

    echo -e "\n${BOLD}${GREEN}================================================================================"
    echo "                              BUILD SUMMARY                                     "
    echo "================================================================================${RESET}"
    echo -e "${BOLD}Target Command:${RESET}     $COMMAND"
    echo -e "${BOLD}Variant Filter:${RESET}     $VARIANT"
    echo -e "${BOLD}Total Duration:${RESET}     $(format_time $total_duration)"

    # Check for produced APKs
    local apk_dir="${PROJECT_ROOT}/app/build/outputs/apk"
    if [[ -d "$apk_dir" ]]; then
        local apks
        apks=$(find "$apk_dir" -type f -name "*.apk" 2>/dev/null || true)
        if [[ -n "$apks" ]]; then
            echo -e "\n${BOLD}${CYAN}Generated APK Packages:${RESET}"
            while IFS= read -r apk; do
                if [[ -n "$apk" ]]; then
                    local size
                    size=$(human_readable_size "$apk")
                    echo -e "  - ${GREEN}${apk#$PROJECT_ROOT/}${RESET} ${DIM}(${size})${RESET}"
                fi
            done <<< "$apks"
        fi
    fi

    # Check for produced AABs
    local bundle_dir="${PROJECT_ROOT}/app/build/outputs/bundle"
    if [[ -d "$bundle_dir" ]]; then
        local aabs
        aabs=$(find "$bundle_dir" -type f -name "*.aab" 2>/dev/null || true)
        if [[ -n "$aabs" ]]; then
            echo -e "\n${BOLD}${CYAN}Generated App Bundles (AAB):${RESET}"
            while IFS= read -r aab; do
                if [[ -n "$aab" ]]; then
                    local size
                    size=$(human_readable_size "$aab")
                    echo -e "  - ${GREEN}${aab#$PROJECT_ROOT/}${RESET} ${DIM}(${size})${RESET}"
                fi
            done <<< "$aabs"
        fi
    fi

    # Check for test reports (every module)
    local reports
    reports=$(find "$PROJECT_ROOT" -maxdepth 6 -type f -path "*/build/reports/tests/*/index.html" -not -path "*/build-logic/*" 2>/dev/null | sort || true)
    if [[ -n "$reports" ]]; then
        echo -e "\n${BOLD}${CYAN}Test Reports:${RESET}"
        while IFS= read -r report; do
            if [[ -n "$report" ]]; then
                echo -e "  - ${WHITE}${report#$PROJECT_ROOT/}${RESET}"
            fi
        done <<< "$reports"
    fi

    # Check for lint reports
    local lint_reports_dir="${PROJECT_ROOT}/app/build/reports"
    if [[ -d "$lint_reports_dir" ]]; then
        local lint_reports
        lint_reports=$(find "$lint_reports_dir" -maxdepth 1 -type f -name "lint-results*.html" 2>/dev/null || true)
        if [[ -n "$lint_reports" ]]; then
            echo -e "\n${BOLD}${CYAN}Lint Reports:${RESET}"
            while IFS= read -r report; do
                if [[ -n "$report" ]]; then
                    echo -e "  - ${WHITE}${report#$PROJECT_ROOT/}${RESET}"
                fi
            done <<< "$lint_reports"
        fi
    fi

    echo -e "\n${BOLD}${GREEN}✔ All requested operations finished successfully!${RESET}\n"
}

# ------------------------------------------------------------------------------
# Build Orchestrator
# ------------------------------------------------------------------------------
build_pipeline() {
    check_prerequisites

    # 1. Clean if requested or if clean command
    if [[ $FLAG_CLEAN -eq 1 || "$COMMAND" == "clean" ]]; then
        run_gradle "Cleaning build cache and output directories" clean
        if [[ "$COMMAND" == "clean" ]]; then
            print_summary
            return 0
        fi
    fi

    # 2. Stop daemon command
    if [[ "$COMMAND" == "stop-daemon" ]]; then
        run_gradle "Stopping Gradle daemons" --stop
        return 0
    fi

    # 3. Diagnostics
    if [[ "$COMMAND" == "diagnostics" ]]; then
        run_diagnostics
        return 0
    fi

    # 4. Stability Dump
    if [[ "$COMMAND" == "stability-dump" ]]; then
        case "$VARIANT" in
            debug)
                run_gradle "Updating Compose stability dump (Debug)" debugStabilityDump
                ;;
            release)
                run_gradle "Updating Compose stability dump (Release)" releaseStabilityDump
                ;;
            *)
                run_gradle "Updating Compose stability dump (All variants)" stabilityDump
                ;;
        esac
        print_summary
        return 0
    fi

    # 5. Stability Check
    if [[ "$COMMAND" == "stability" || "$COMMAND" == "check" || "$COMMAND" == "all" || $FLAG_STABILITY -eq 1 ]]; then
        if [[ $SKIP_STABILITY -eq 0 ]]; then
            case "$VARIANT" in
                debug)
                    run_gradle "Running Compose stability check (Debug)" debugStabilityCheck
                    ;;
                release)
                    run_gradle "Running Compose stability check (Release)" releaseStabilityCheck
                    ;;
                *)
                    run_gradle "Running Compose stability checks" stabilityCheck
                    ;;
            esac
            if [[ "$COMMAND" == "stability" ]]; then
                print_summary
                return 0
            fi
        fi
    fi

    # 6. Lint Tasks
    if [[ "$COMMAND" == "lint-fix" ]]; then
        run_gradle "Running Android Lint with automatic fixes" :app:lintFix
        print_summary
        return 0
    fi

    if [[ "$COMMAND" == "lint" || "$COMMAND" == "check" || "$COMMAND" == "all" || $FLAG_LINT -eq 1 ]]; then
        if [[ $SKIP_LINT -eq 0 ]]; then
            case "$VARIANT" in
                debug)
                    run_gradle "Running Android Lint (Debug)" :app:lintDebug
                    ;;
                release)
                    run_gradle "Running Android Lint (Release)" :app:lintRelease
                    ;;
                *)
                    run_gradle "Running Android Lint (All variants)" :app:lint
                    ;;
            esac
            if [[ "$COMMAND" == "lint" ]]; then
                print_summary
                return 0
            fi
        fi
    fi

    # 7. Unit Tests
    if [[ "$COMMAND" == "test" || "$COMMAND" == "check" || "$COMMAND" == "all" || $FLAG_TEST -eq 1 ]]; then
        if [[ $SKIP_TESTS -eq 0 ]]; then
            case "$VARIANT" in
                debug)
                    run_gradle "Running Unit Tests (Debug)" testDebugUnitTest :common-core:test
                    ;;
                release)
                    run_gradle "Running Unit Tests (Release)" testReleaseUnitTest :common-core:test
                    ;;
                *)
                    run_gradle "Running Unit Tests (All variants)" test
                    ;;
            esac
            if [[ "$COMMAND" == "test" ]]; then
                print_summary
                return 0
            fi
        fi
    fi

    # Check command finished if 'check'
    if [[ "$COMMAND" == "check" ]]; then
        print_summary
        return 0
    fi

    # 8. Connected / Instrumented Tests
    if [[ "$COMMAND" == "connected-test" ]]; then
        case "$VARIANT" in
            release)
                run_gradle "Running Connected Instrumented Tests (Release)" :app:connectedReleaseAndroidTest
                ;;
            *)
                run_gradle "Running Connected Instrumented Tests (Debug)" :app:connectedDebugAndroidTest
                ;;
        esac
        print_summary
        return 0
    fi

    # 9. Install on connected device
    if [[ "$COMMAND" == "install-debug" ]]; then
        run_gradle "Installing Debug APK to connected device" :app:installDebug
        print_summary
        return 0
    fi

    # 10. Assemble / Packaging (APKs and/or AABs)
    local assemble_tasks=()

    if [[ "$COMMAND" == "bundle" ]]; then
        case "$VARIANT" in
            debug)
                assemble_tasks+=(":app:bundleDebug")
                ;;
            release)
                assemble_tasks+=(":app:bundleRelease")
                ;;
            *)
                assemble_tasks+=(":app:bundle")
                ;;
        esac
    elif [[ "$COMMAND" == "debug" ]]; then
        assemble_tasks+=(":app:assembleDebug")
    elif [[ "$COMMAND" == "release" ]]; then
        assemble_tasks+=(":app:assembleRelease")
        assemble_tasks+=(":app:bundleRelease")
    else
        # assemble or all
        if [[ $FLAG_BUILD_APK -eq 1 ]]; then
            case "$VARIANT" in
                debug)
                    assemble_tasks+=(":app:assembleDebug")
                    ;;
                release)
                    assemble_tasks+=(":app:assembleRelease")
                    ;;
                *)
                    assemble_tasks+=(":app:assemble")
                    ;;
            esac
        fi

        if [[ $FLAG_BUILD_AAB -eq 1 ]]; then
            case "$VARIANT" in
                debug)
                    assemble_tasks+=(":app:bundleDebug")
                    ;;
                release)
                    assemble_tasks+=(":app:bundleRelease")
                    ;;
                *)
                    assemble_tasks+=(":app:bundle")
                    ;;
            esac
        fi
    fi

    if [[ ${#assemble_tasks[@]} -gt 0 ]]; then
        run_gradle "Building and packaging application artifacts" "${assemble_tasks[@]}"
    fi

    print_summary
}

# ------------------------------------------------------------------------------
# Script Entry Point
# ------------------------------------------------------------------------------
main() {
    parse_arguments "$@"
    build_pipeline
}

main "$@"
