package com.dhimandasgupta.notemark.common.extensions.coroutines

import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.retryWhen
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.math.max
import kotlin.math.min
import kotlin.math.pow
import kotlin.random.Random
import kotlin.time.Clock
import kotlin.time.Duration
import kotlin.time.Duration.Companion.seconds

/**
 * Creates a flow that emits a single value produced by the provided suspend function.
 *
 * @param producer A suspend function that generates a value to be emitted by the resulting flow.
 * @return A flow that emits the value produced by the suspend function.
 */
fun <T> flowOf(producer: suspend () -> T) = flow { emit(producer()) }

val neverFlow = flow<Nothing> { suspendCancellableCoroutine<Unit> { } }

/**
 * Creates an infinite flow that continuously emits values generated by the given producer function.
 * The producer function is invoked repeatedly in a loop, and the results are emitted into the flow.
 *
 * @param producer A suspending function that produces values to emit into the flow.
 *                 This function will be called repeatedly to generate new values.
 * @return A flow that emits values produced by the producer function indefinitely.
 */
fun <T> infiniteFlowOf(producer: suspend () -> T) = flow<T> {
    while (true) {
        emit(producer())
    }
}

/**
 * Collects elements from the upstream flow and invokes [action] with a list of elements
 * as soon as [batchSize] elements are accumulated. When the flow terminates
 * (normal completion, cancellation, or exception), [action] is invoked with
 * the remaining collected elements.
 *
 * Elements are emitted downstream immediately as they are received from upstream.
 */
fun <T> Flow<T>.onEachBatch(
    batchSize: Int,
    action: suspend (List<T>) -> Unit
): Flow<T> = flow {
    var collected = mutableListOf<T>()
    try {
        collect { value ->
            collected.add(value)
            if (collected.size >= batchSize) {
                action(collected.also { collected = mutableListOf() })
            }
            emit(value)
        }
    } finally {
        if (collected.isNotEmpty()) {
            action(collected)
        }
    }
}

/**
 * Emits value every [period], if there is one. Emits immediately, if time between
 * two consecutively emitted values is greater or equals [period]
 * */
fun <T> Flow<T>.enqueueWithDelay(period: Duration = 1.seconds): Flow<T> {
    val periodMs = period.inWholeMilliseconds
    return flow {
        var lastEmitTime = 0L
        this@enqueueWithDelay.collect { value ->
            val currentTime = currentTimeMillis()
            val elapsedTime = currentTime - lastEmitTime

            val waitTime = periodMs - elapsedTime
            if (waitTime > 0) delay(waitTime)

            emit(value)
            lastEmitTime = currentTimeMillis()
        }
    }
}

private fun currentTimeMillis(): Long = Clock.System.now().toEpochMilliseconds()

fun <T> Flow<T>.retryBackoff(
    minDelay: Duration,
    maxDelay: Duration = Duration.INFINITE,
    maxAttempts: Int = Int.MAX_VALUE,
    backoffFactor: Double = 2.0,
    transient: Boolean = true,
    jitterFactor: Double = 0.1,
    random: Random = Random,
    successAfterRetry: suspend (attempts: Int) -> Unit = {},
    beforeRetry: suspend (cause: Throwable, currentAttempts: Int, totalAttempts: Int) -> Unit = { _, _, _ -> },
    retriesExhausted: suspend (cause: Throwable) -> Unit = {},
    retryCondition: suspend (cause: Throwable, currentAttempts: Int, totalAttempts: Int) -> Boolean = { _, _, _, -> true }
): Flow<T> {
    require(jitterFactor in 0.0..1.0)
    require(maxAttempts > 0)
    require(backoffFactor > 1.0)
    require(minDelay in Duration.ZERO..maxDelay)

    return flow {
        var attemptsInRow = 0
        var isRetrying = false
        this@retryBackoff
            .retryWhen { cause, totalAttempts ->
                isRetrying = true
                val currentAttempts = if (transient) attemptsInRow else totalAttempts.toInt()
                if (currentAttempts == maxAttempts) {
                    retriesExhausted(cause)
                    return@retryWhen false
                }

                val effectiveDelay =
                    calculateBackoffDelay(minDelay, maxDelay, currentAttempts, jitterFactor, random, backoffFactor)

                beforeRetry(cause, currentAttempts, totalAttempts.toInt())
                val shouldRetry = retryCondition(cause, currentAttempts, totalAttempts.toInt())
                if (!shouldRetry) return@retryWhen false
                delay(effectiveDelay.toLong())
                attemptsInRow++
                true
            }
            .onEach {
                if (isRetrying) {
                    successAfterRetry(attemptsInRow)
                    isRetrying = false
                }
                if (transient) attemptsInRow = 0
            }
            .collect(this)
    }
}

// TODO: Publish once unit-tested
internal suspend fun <T> retryBackoff(
    minDelay: Duration,
    maxDelay: Duration = Duration.INFINITE,
    maxAttempts: Int = Int.MAX_VALUE,
    backoffFactor: Double = 2.0,
    jitterFactor: Double = 0.1,
    random: Random = Random,
    beforeRetry: suspend (cause: Throwable, attempts: Int) -> Unit = { _, _ -> },
    retriesExhausted: suspend (cause: Throwable) -> Unit = {},
    block: () -> T,
): T {
    require(jitterFactor in 0.0..1.0)
    require(maxAttempts > 0)
    require(backoffFactor > 1.0)
    require(minDelay in Duration.ZERO..maxDelay)

    return retryWhen(
        predicate = { cause, currentAttempts ->
            if (currentAttempts == maxAttempts) {
                retriesExhausted(cause)
                return@retryWhen false
            }

            val effectiveDelay = calculateBackoffDelay(
                minDelay, maxDelay, currentAttempts, jitterFactor, random,
                backoffFactor
            )
            beforeRetry(cause, currentAttempts)
            delay(effectiveDelay.toLong())
            true
        },
        operation = block,
    )
}

private fun calculateBackoffDelay(
    minDelay: Duration,
    maxDelay: Duration,
    currentAttempts: Int,
    jitterFactor: Double,
    random: Random,
    backoffFactor: Double,
): Double {
    val minDelayMillis = minDelay.inWholeMilliseconds.toDouble()
    val maxDelayMillis = maxDelay.inWholeMilliseconds.toDouble()
    val baseDelay = (minDelayMillis * backoffFactor.pow(currentAttempts))
        .coerceAtMost(maxDelayMillis)

    return if (jitterFactor == 0.0) {
        baseDelay
    } else {
        val jitterOffset = baseDelay * jitterFactor
        val minJitter = max(minDelayMillis, baseDelay - jitterOffset)
        val maxJitter = min(maxDelayMillis, baseDelay + jitterOffset)
        if (minJitter == maxJitter) {
            minJitter
        } else {
            random.nextDouble(minJitter, maxJitter)
        }
    }
}